// Code generated by mockery v1.0.0. DO NOT EDIT.

package mock

import mock "github.com/stretchr/testify/mock"
import user "github.com/app/realworld/model/user"

// AuthMiddle is an autogenerated mock type for the AuthMiddle type
type AuthMiddle struct {
	mock.Mock
}

// Authenticate provides a mock function with given fields: email, password
func (_m *AuthMiddle) Authenticate(email string, password string) (user.LoginInfo, string, error) {
	ret := _m.Called(email, password)

	var r0 user.LoginInfo
	if rf, ok := ret.Get(0).(func(string, string) user.LoginInfo); ok {
		r0 = rf(email, password)
	} else {
		r0 = ret.Get(0).(user.LoginInfo)
	}

	var r1 string
	if rf, ok := ret.Get(1).(func(string, string) string); ok {
		r1 = rf(email, password)
	} else {
		r1 = ret.Get(1).(string)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string, string) error); ok {
		r2 = rf(email, password)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
